spring:
  application:
    name: intershop
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=intershop
    user: postgres
    password: postgres
    change-log: classpath:/db/changelog/db.changelog-master.xml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=intershop
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  webflux:
    base-path: /intershop
    hiddenmethod:
      filter:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_SERVICE_NAME:localhost:8090}/realms/master
        registration:
          intershop-service:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: intershop-service
            client-secret: sEoY6QTWf0XA9JWXU5LxBHy1zjc3U1vt
            scope: profile
            clientAuthenticationMethod: client_secret_post
  thymeleaf:
    encoding: UTF-8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cache:
    redis:
      time-to-live: PT1M

image:
  folder:
    server:
      path: ${IMAGES_DIR:${user.dir}/client-service/uploaded-images}
    client:
      path: /image/

api:
  client:
    payment-service:
      url: http://localhost:8082
