openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
  description: Реактивный REST API для получения баланса и осуществления платежа.

servers:
  - url: http://localhost:8082
    description: Локальный сервер

paths:
  /payment/balance:
    get:
      summary: Получение текущего баланса
      operationId: getBalance
      tags:
        - payment
      responses:
        '200':
          description: Баланс успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
        '5XX':
          description: Ошибка на стороне сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /payment/pay:
    post:
      summary: Проведение платежа
      operationId: processPayment
      tags:
        - payment
      requestBody:
        description: Сумма для списания
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amount'
      responses:
        '200':
          description: Платёж успешно выполнен
        '400':
          description: Недостаточно средств
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '5XX':
          description: Ошибка на стороне сервиса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    Balance:
      type: number
      example: 1500.00

    Amount:
      type: number
      example: 300.00

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Недостаточно средств для проведения платежа